/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonyRouteImport } from './routes/testimony'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RestorationRouteImport } from './routes/restoration'
import { Route as PrayerRouteImport } from './routes/prayer'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as GivingRouteImport } from './routes/giving'
import { Route as CounselRouteImport } from './routes/counsel'
import { Route as ConfessRouteImport } from './routes/confess'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LookupIndexRouteImport } from './routes/lookup.index'
import { Route as LookupTokenRouteImport } from './routes/lookup.$token'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChambersRouteImport } from './routes/_authenticated/chambers'
import { Route as AuthenticatedInboxIndexRouteImport } from './routes/_authenticated/inbox.index'
import { Route as AuthenticatedInboxIdRouteImport } from './routes/_authenticated/inbox.$id'
import { Route as AuthenticatedChambersIdRouteImport } from './routes/_authenticated/chambers.$id'
import { Route as AuthenticatedAdminInvitesRouteImport } from './routes/_authenticated/admin.invites'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'

const TestimonyRoute = TestimonyRouteImport.update({
  id: '/testimony',
  path: '/testimony',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RestorationRoute = RestorationRouteImport.update({
  id: '/restoration',
  path: '/restoration',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRoute = PrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const GivingRoute = GivingRouteImport.update({
  id: '/giving',
  path: '/giving',
  getParentRoute: () => rootRouteImport,
} as any)
const CounselRoute = CounselRouteImport.update({
  id: '/counsel',
  path: '/counsel',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfessRoute = ConfessRouteImport.update({
  id: '/confess',
  path: '/confess',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupIndexRoute = LookupIndexRouteImport.update({
  id: '/lookup/',
  path: '/lookup/',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupTokenRoute = LookupTokenRouteImport.update({
  id: '/lookup/$token',
  path: '/lookup/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChambersRoute = AuthenticatedChambersRouteImport.update({
  id: '/chambers',
  path: '/chambers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxIndexRoute = AuthenticatedInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxIdRoute = AuthenticatedInboxIdRouteImport.update({
  id: '/inbox/$id',
  path: '/inbox/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChambersIdRoute = AuthenticatedChambersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedChambersRoute,
} as any)
const AuthenticatedAdminInvitesRoute =
  AuthenticatedAdminInvitesRouteImport.update({
    id: '/admin/invites',
    path: '/admin/invites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confess': typeof ConfessRoute
  '/counsel': typeof CounselRoute
  '/giving': typeof GivingRoute
  '/partners': typeof PartnersRoute
  '/prayer': typeof PrayerRoute
  '/restoration': typeof RestorationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimony': typeof TestimonyRoute
  '/chambers': typeof AuthenticatedChambersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lookup/$token': typeof LookupTokenRoute
  '/lookup/': typeof LookupIndexRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/chambers/$id': typeof AuthenticatedChambersIdRoute
  '/inbox/$id': typeof AuthenticatedInboxIdRoute
  '/inbox/': typeof AuthenticatedInboxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confess': typeof ConfessRoute
  '/counsel': typeof CounselRoute
  '/giving': typeof GivingRoute
  '/partners': typeof PartnersRoute
  '/prayer': typeof PrayerRoute
  '/restoration': typeof RestorationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimony': typeof TestimonyRoute
  '/chambers': typeof AuthenticatedChambersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lookup/$token': typeof LookupTokenRoute
  '/lookup': typeof LookupIndexRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/chambers/$id': typeof AuthenticatedChambersIdRoute
  '/inbox/$id': typeof AuthenticatedInboxIdRoute
  '/inbox': typeof AuthenticatedInboxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/confess': typeof ConfessRoute
  '/counsel': typeof CounselRoute
  '/giving': typeof GivingRoute
  '/partners': typeof PartnersRoute
  '/prayer': typeof PrayerRoute
  '/restoration': typeof RestorationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimony': typeof TestimonyRoute
  '/_authenticated/chambers': typeof AuthenticatedChambersRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/lookup/$token': typeof LookupTokenRoute
  '/lookup/': typeof LookupIndexRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/_authenticated/chambers/$id': typeof AuthenticatedChambersIdRoute
  '/_authenticated/inbox/$id': typeof AuthenticatedInboxIdRoute
  '/_authenticated/inbox/': typeof AuthenticatedInboxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/confess'
    | '/counsel'
    | '/giving'
    | '/partners'
    | '/prayer'
    | '/restoration'
    | '/sitemap.xml'
    | '/testimony'
    | '/chambers'
    | '/dashboard'
    | '/lookup/$token'
    | '/lookup/'
    | '/admin/audit'
    | '/admin/invites'
    | '/chambers/$id'
    | '/inbox/$id'
    | '/inbox/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/confess'
    | '/counsel'
    | '/giving'
    | '/partners'
    | '/prayer'
    | '/restoration'
    | '/sitemap.xml'
    | '/testimony'
    | '/chambers'
    | '/dashboard'
    | '/lookup/$token'
    | '/lookup'
    | '/admin/audit'
    | '/admin/invites'
    | '/chambers/$id'
    | '/inbox/$id'
    | '/inbox'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/confess'
    | '/counsel'
    | '/giving'
    | '/partners'
    | '/prayer'
    | '/restoration'
    | '/sitemap.xml'
    | '/testimony'
    | '/_authenticated/chambers'
    | '/_authenticated/dashboard'
    | '/lookup/$token'
    | '/lookup/'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/invites'
    | '/_authenticated/chambers/$id'
    | '/_authenticated/inbox/$id'
    | '/_authenticated/inbox/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConfessRoute: typeof ConfessRoute
  CounselRoute: typeof CounselRoute
  GivingRoute: typeof GivingRoute
  PartnersRoute: typeof PartnersRoute
  PrayerRoute: typeof PrayerRoute
  RestorationRoute: typeof RestorationRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimonyRoute: typeof TestimonyRoute
  LookupTokenRoute: typeof LookupTokenRoute
  LookupIndexRoute: typeof LookupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimony': {
      id: '/testimony'
      path: '/testimony'
      fullPath: '/testimony'
      preLoaderRoute: typeof TestimonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restoration': {
      id: '/restoration'
      path: '/restoration'
      fullPath: '/restoration'
      preLoaderRoute: typeof RestorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giving': {
      id: '/giving'
      path: '/giving'
      fullPath: '/giving'
      preLoaderRoute: typeof GivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsel': {
      id: '/counsel'
      path: '/counsel'
      fullPath: '/counsel'
      preLoaderRoute: typeof CounselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confess': {
      id: '/confess'
      path: '/confess'
      fullPath: '/confess'
      preLoaderRoute: typeof ConfessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup/': {
      id: '/lookup/'
      path: '/lookup'
      fullPath: '/lookup/'
      preLoaderRoute: typeof LookupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup/$token': {
      id: '/lookup/$token'
      path: '/lookup/$token'
      fullPath: '/lookup/$token'
      preLoaderRoute: typeof LookupTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chambers': {
      id: '/_authenticated/chambers'
      path: '/chambers'
      fullPath: '/chambers'
      preLoaderRoute: typeof AuthenticatedChambersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox/': {
      id: '/_authenticated/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AuthenticatedInboxIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox/$id': {
      id: '/_authenticated/inbox/$id'
      path: '/inbox/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof AuthenticatedInboxIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chambers/$id': {
      id: '/_authenticated/chambers/$id'
      path: '/$id'
      fullPath: '/chambers/$id'
      preLoaderRoute: typeof AuthenticatedChambersIdRouteImport
      parentRoute: typeof AuthenticatedChambersRoute
    }
    '/_authenticated/admin/invites': {
      id: '/_authenticated/admin/invites'
      path: '/admin/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AuthenticatedAdminInvitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedChambersRouteChildren {
  AuthenticatedChambersIdRoute: typeof AuthenticatedChambersIdRoute
}

const AuthenticatedChambersRouteChildren: AuthenticatedChambersRouteChildren = {
  AuthenticatedChambersIdRoute: AuthenticatedChambersIdRoute,
}

const AuthenticatedChambersRouteWithChildren =
  AuthenticatedChambersRoute._addFileChildren(
    AuthenticatedChambersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChambersRoute: typeof AuthenticatedChambersRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminInvitesRoute: typeof AuthenticatedAdminInvitesRoute
  AuthenticatedInboxIdRoute: typeof AuthenticatedInboxIdRoute
  AuthenticatedInboxIndexRoute: typeof AuthenticatedInboxIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChambersRoute: AuthenticatedChambersRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminInvitesRoute: AuthenticatedAdminInvitesRoute,
  AuthenticatedInboxIdRoute: AuthenticatedInboxIdRoute,
  AuthenticatedInboxIndexRoute: AuthenticatedInboxIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConfessRoute: ConfessRoute,
  CounselRoute: CounselRoute,
  GivingRoute: GivingRoute,
  PartnersRoute: PartnersRoute,
  PrayerRoute: PrayerRoute,
  RestorationRoute: RestorationRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimonyRoute: TestimonyRoute,
  LookupTokenRoute: LookupTokenRoute,
  LookupIndexRoute: LookupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
